export const CURRENT_GAME_VERSION = 2;
export const ELECTRICITY_COST_PER_WATT_SECOND = 0.000_01;
export const VIOLATION_RECOVERY_RATE = 0.5;
export const BANKRUPTCY_THRESHOLD = -10_000;
export const FULFILLMENT_EPSILON = 1e-9;
